doctrine:
  dbal:
    connections:
      household:
        driver: '%env(HOUSEHOLD_DATABASE_DRIVER)%'
        user: '%env(HOUSEHOLD_DATABASE_USER)%'
        password: '%env(HOUSEHOLD_DATABASE_PASSWORD)%'
        dbname: '%env(HOUSEHOLD_DATABASE_NAME)%'
        host: '%env(HOUSEHOLD_DATABASE_HOST)%'
        port: '%env(HOUSEHOLD_DATABASE_PORT)%'

    types:
      duty_id: App\Household\Duty\Infrastructure\Persistence\Doctrine\DutyIdType
      duty_variant_id: App\Household\DutyVariant\Infrastructure\Persistence\Doctrine\DutyVariantIdType

  orm:
    auto_generate_proxy_classes: true
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      Duty:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/Duty/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\Duty\Domain'
      DutyVariant:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/DutyVariant/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\DutyVariant\Domain'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
