doctrine:
  dbal:
    connections:
      household:
        driver: '%env(HOUSEHOLD_DATABASE_DRIVER)%'
        user: '%env(HOUSEHOLD_DATABASE_USER)%'
        password: '%env(HOUSEHOLD_DATABASE_PASSWORD)%'
        dbname: '%env(HOUSEHOLD_DATABASE_NAME)%'
        host: '%env(HOUSEHOLD_DATABASE_HOST)%'
        port: '%env(HOUSEHOLD_DATABASE_PORT)%'

    types:
      uuid: App\Shared\Infrastructure\Persistence\Doctrine\BasicIdType
      task_id: App\Household\Task\Infrastructure\Persistence\Doctrine\TaskIdType
      user_id: App\Household\Auth\Infrastructure\Persistence\Doctrine\UserIdType
      membership_id: App\Household\Membership\Infrastructure\Persistence\Doctrine\MembershipIdType
      listing_id: App\Household\Listing\Infrastructure\Persistence\Doctrine\ListingIdType
      list_item_id: App\Household\ListItem\Infrastructure\Persistence\Doctrine\ListItemIdType

  orm:
    auto_generate_proxy_classes: true
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    mappings:
      Task:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/Task/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\Task\Domain'
      Auth:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/Auth/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\Auth\Domain'
      Membership:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/Membership/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\Membership\Domain'
      Listing:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/Listing/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\Listing\Domain'
      ListItem:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/../../../src/Household/ListItem/Infrastructure/Persistence/Doctrine'
        prefix: 'App\Household\ListItem\Domain'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool
