framework:
  secret: '%env(APP_SECRET)%'
  http_method_override: false

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  php_errors:
    log: true

  validation:
    email_validation_mode: html5

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file

    validation:
      not_compromised_password: false

when@prod:
  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
