parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true


  App\:
    resource: '../../../../src'

  Apps\Household\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  App\Household\Duty\Domain\DutyRepository: '@App\Household\Duty\Infrastructure\Persistence\MySqlDutyRepository'

  App\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }
